version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
  server:
    image: node:latest
    working_dir: /app/server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app/server
    command: sh -c "sleep 5s && npm install && npm run dev"
    depends_on:
      - mssql